# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:mono-3.4.4

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: ls -lh
      - run: cd ./godot && ls -lh
      # The base Docker image seems to have the templates in an outdated location, so link them:
      - run: mkdir -p /github/home/.local/share/godot
      - run: ln -s /root/.local/share/godot/templates/ /github/home/.local/share/godot/templates
      - run: godot ./godot/project.godot --export "HTML5"
      - run: cd ./godot/.export/HTML5 && ls -lh