name: ExportHTML5

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.x

      - name: Install the Godot Mono Headless binary
        run: |
          cd ./.github/downloads
          unzip ./Godot_v3.5.1-stable_mono_linux_headless_64.zip
          mv ./Godot_v3.5.1-stable_mono_linux_headless_64/* /usr/local/bin/
          mv /usr/local/bin/Godot_v3.5.1-stable_mono_linux_headless.64 /usr/local/bin/godot

      #- run: godot --help # Works but exits with code 255 anyway

      - name: Install the Godot export templates
        run: |
          cd ./.github/downloads
          unzip ./Godot_v3.5.1-stable_mono_export_templates.zip
          mkdir --parents /home/runner/.local/share/godot/templates
          mv ./Godot_v3.5.1-stable_mono_export_templates/templates /home/runner/.local/share/godot/templates/3.5.1.stable.mono

      # The export command can fail but still exit with status code 0.
      # Specifically, in the case of a C# compile error the exit code will be 0 but stderr will have a message.
      # So here we redirect stderr and verify that it is empty.
      - name: Export project to HTML5
        run: |
          cd ./godot
          mkdir --parents ./.export/HTML5
          godot ./project.godot --export "HTML5" 2> ./errlog.txt
          ls -lh
          cd .export/HTML5
          ls -lh

      # Be careful! Using `-s` with `&&` and `||` is tricky; I wrote many incorrect versions.
      # Use `if` instead which is much easier to get correct.
      - name: Verify stderr was empty
        run: |
          cd ./godot
          cat ./errlog.txt
          if [ -s ./errlog.txt ]; then exit 55; else echo looks good; fi

      - uses: actions/upload-artifact@v3
        with:
          name: ff2-html5
          path: ./godot/.export/HTML5